"""
llm/prompt_templates.py
-----------------------
System & user prompt templates that instruct Groq to produce
the full 11-section legal analysis report.
"""

SYSTEM_PROMPT = """You are LexBot, an elite Indian legal AI assistant with expert knowledge of:
- Indian Penal Code (IPC)
- Code of Criminal Procedure (CrPC)
- Code of Civil Procedure (CPC)
- Constitutional Law

You will receive:
1. A CASE DESCRIPTION from the user
2. RETRIEVED LEGAL SECTIONS from the RAG database

Your task is to produce a structured, professional legal analysis report with EXACTLY these 11 sections.
Use the retrieved sections as your primary legal authority. Always cite specific section numbers.
Be thorough, professional, and use clear language that both lawyers and laypeople can understand.
"""

_ANALYSIS_TEMPLATE = """
=== RETRIEVED LEGAL SECTIONS (from RAG) ===
{rag_context}
============================================

=== CASE DESCRIPTION ===
{case_description}
========================

Generate a complete legal analysis report with the following 11 sections.
Use ONLY the retrieved legal sections above as your legal basis.

---

## 1. CASE SUMMARY
### Facts of the Case
[Summarize the key facts in bullet points]

### Key Events
[Timeline or key events]

### Parties Involved
[Petitioner / Respondent / Other parties]

---

## 2. LEGAL CLASSIFICATION
[State clearly: Criminal Law (IPC) / Civil Law (CPC) / Procedural Law (CrPC) / Constitutional / Mixed]
[One paragraph explanation of why]

---

## 3. APPLICABLE LAWS (from RAG)
[List ALL retrieved sections that apply, in this format:]
- **[Source] Section [X]** – [Title]: [How it applies to this case]
[Include all relevant sections from the RAG context above]

---

## 4. LEGAL ANALYSIS
[Apply each applicable law to the facts of the case]
[Explain the legal elements that must be proven]
[Discuss how the facts satisfy or fail to satisfy those elements]

---

## 5. ARGUMENTS

### For the Petitioner / Prosecution
[3-5 strong arguments supporting the case]

### For the Respondent / Defense
[3-5 defense arguments]

---

## 6. OPPOSITION STRATEGY
[What will the opposing side argue?]
[Key weaknesses in the petitioner's case]
[How to counter those weaknesses]

---

## 7. CROSS EXAMINATION QUESTIONS

### Questions TO ASK the opponent's witnesses
[5-7 sharp cross-examination questions]

### Questions the OPPONENT may ask
[5-7 questions the other side will likely ask your witness]

---

## 8. RISK ANALYSIS

### Strengths
[Bullet list of case strengths]

### Weaknesses
[Bullet list of case weaknesses]

### Key Risks
[Major legal risks that could affect the outcome]

---

## 9. CASE COMPLEXITY & ESTIMATED FEES

| Factor | Details |
|--------|---------|
| Complexity | Low / Medium / High |
| Estimated Hearings | X-Y hearings |
| Approx. Legal Fees | Rs. X – Rs. Y |
| Time to Resolution | X-Y months/years |
| Court Level | District / High Court / Supreme Court |

---

## 10. OUTCOME PREDICTION

**Prediction:** [X]% probability of success for petitioner

**Reasoning:**
[3-4 specific reasons for this prediction based on the law and facts]

**Key Determining Factors:**
[What will ultimately decide the case]

---

## 11. VALIDATION & DISCLAIMER

**Legal Basis:** This analysis is based on the following retrieved legal sections:
{section_citations}

**Important Notice:**
- This analysis is generated by an AI system using RAG (Retrieval-Augmented Generation)
- All legal sections cited are from the official IPC, CrPC, and CPC databases
- This report is for informational and educational purposes only
- It does not constitute formal legal advice
- Please consult a qualified advocate before taking any legal action
- Specific facts of your case may require interpretation by a licensed legal professional
"""


def build_legal_analysis_prompt(case_description: str, rag_docs: list) -> tuple:
    """
    Build (system_prompt, user_prompt) for the full 11-section analysis.

    Parameters
    ----------
    case_description : str  – the user's case description
    rag_docs         : list – list of doc dicts from vector_store.search()

    Returns
    -------
    (system_prompt, user_prompt) tuple
    """
    # Build the RAG context block
    context_parts = []
    citations     = []
    for i, doc in enumerate(rag_docs, 1):
        context_parts.append(
            f"[{i}] {doc['source']} Section {doc['section']} — {doc['title']}\n"
            f"{doc['content']}\n"
            f"{'─' * 60}"
        )
        citations.append(f"- {doc['source']} Section {doc['section']} ({doc['title']})")

    rag_context      = "\n".join(context_parts)
    section_citations = "\n".join(citations)

    user_prompt = _ANALYSIS_TEMPLATE.format(
        rag_context=rag_context,
        case_description=case_description,
        section_citations=section_citations,
    )

    return SYSTEM_PROMPT, user_prompt
